org: levicosta201
app: ms-get-data-table-a
service: ms-get-data-table-a
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
